---
title: "Consolidate_files_code"
output: html_document
date: "2023-08-16"
---

# Combine data
These are the codes to consolidate all the files into a single file. 

There are four behavioral tasks:
- Typing speed task
- Digit Span task
- Visual Pattern task
- Multiplication production task

```{r}
# Load library
library(tidyverse)

# List all CSV files in the "raw_data" folder
csv_files <- list.files("demo_data", pattern = "*.csv", full.names = TRUE)

# Read and consolidate data using tidyverse
consolidated_data <- map_df(csv_files, ~ read_csv(.x, col_types = cols(session = col_character())))

```

# Demographic data from Qualtrics

```{r}
library(lubridate)

# List all CSV files in the "raw_data" folder
csv_files <- list.files("demo_data", pattern = "*.csv", full.names = TRUE)

# Read and consolidate data using tidyverse
demo_data <- map_df(csv_files, ~ read_csv(.x)) %>% 
  slice(3:n()) %>% 
  select(RecordedDate, participant, dob_1, dob_2, dob_3, 
         gender, nationality, ethnicity, handedness, 
         eduLevel, employment,
         Medicalhistory,developmentHist,nativelanguage, 
         ParentsEdu, income) %>% 
  filter(!is.na(participant))

# Change dob variable to "mm/dd/year" format and calculate participants' ages
demo_data <- demo_data %>%
  filter(row_number() != 115 & row_number() != 114) %>% 
  mutate(month_numeric = match(tolower(dob_1), tolower(month.name)),
         dob = paste(month_numeric, dob_2, dob_3, sep = "/"),
         recorded_year = year(mdy_hm(RecordedDate)),
         age = ifelse(!is.na(dob_3), recorded_year - as.numeric(dob_3), NA)) %>% 
  select(-dob_1, -dob_2, -dob_3,
         -month_numeric, -recorded_year)

# Construct the full file path including the folder's name
output_file_path <- file.path("consolidated_data", "consolidated_demo_data.csv")

# Write the data frame to the specified file path
write_csv(demo_data, output_file_path)
```


## Typing speed task

```{r}
# Remove all personal information and segregate by task
typing_df <- consolidated_data %>% 
  select(typedNumber, typingRT, answerCorr, participant, group) %>% 
  filter(!typedNumber %in% c(41, 39, 59), !is.na(typedNumber))

# Construct the full file path including the folder's name
output_file_path <- file.path("consolidated_data", "consolidated_typing_data.csv")

# Write the data frame to the specified file path
write_csv(typing_df, output_file_path)
```


## Multiplication production task

```{r}
# Remove all personal information and segregate by task
mult_df <- consolidated_data %>% 
  select(typedAnswer, multiplyRT, multiplyCorr, problem, 
         OperandType, productType, participant, group) %>% 
  filter(!productType %in% c('practiceQ'), !is.na(productType))

# Construct the full file path including the folder's name
output_file_path <- file.path("consolidated_data", "consolidated_mult_data.csv")

# Write the data frame to the specified file path
write_csv(mult_df, output_file_path)
```

## Digit span task (Egner)

```{r}
# Remove all personal information and segregate by task
digitspan_egner_df <- consolidated_data %>% 
  select(digitSpan, digits_audio, EgnerDSrt, EgnerDSscore, participant, group) %>% 
  filter(!is.na(EgnerDSrt))

# Construct the full file path including the folder's name
output_file_path <- file.path("consolidated_data", "consolidated_digit-span-egner_data.csv")

# Write the data frame to the specified file path
write_csv(digitspan_egner_df, output_file_path)
```

## Digit span task (WAIS)

```{r}
# Remove all personal information and segregate by task
digitspan_wais_df <- consolidated_data %>% 
  select(digitSpanWAIS, WAISDSrt, WAISDSresponse, WAISDSscore, participant, group) %>% 
  filter(!is.na(WAISDSrt))

# Construct the full file path including the folder's name
output_file_path <- file.path("consolidated_data", "consolidated_digit-span-wais_data.csv")

# Write the data frame to the specified file path
write_csv(digitspan_wais_df, output_file_path)
```
## Visual Pattern task

```{r}
# Remove all personal information and segregate by task
vpt_df <- consolidated_data %>% 
  select(rows, cols, vptCorrect, noOfBlocks, participant, group) %>% 
  filter(!is.na(vptCorrect))

# Construct the full file path including the folder's name
output_file_path <- file.path("consolidated_data", "consolidated_vpt_data.csv")

# Write the data frame to the specified file path
write_csv(vpt_df, output_file_path)
```
